um982:
  PVTSLNA: 0.05
  GPHPR: 0.05
  # BESTNAVA: 0.05
  CONFIG: "PVTALG MULTI"
um982-1:
  PVTSLNA: 0.1
  GPHPR: 0.1
  BESTNAVA: 0.1
  KSXT: 0.1
  CONFIG: "PVTALG MULTI"
um980:
  PVTSLNA: 1
  GPHPR: 1
  BESTNAVA: 1
  KSXT: 1
