teleop_twist_joy_node:
  ros__parameters:
    axis_linear: # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular: # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 1.0
    scale_angular_turbo:
      x: 2.0

    enable_button: 0 # 'A'
    enable_turbo_button: 1 # 'B'
