- Lat: 37.71942289
  Lon: 127.52545426
- Lat: 37.71948519997
  Lon: 127.525630855402
- Lat: 37.71948975292
  Lon: 127.52543907899
- Lat: 37.7194486396
  Lon: 127.52553092396201
- Lat: 37.719534744742
  Lon: 127.52559114911999
